#!/sbin/sh
echo "" >> /system/build.prop;
echo "#flyme stock hardwareui accel" >> /system/build.prop;
echo "ro.hwui.texture_cache_size=72" >> /system/build.prop;
echo "ro.hwui.layer_cache_size=48" >> /system/build.prop;
echo "ro.hwui.r_buffer_cache_size=8" >> /system/build.prop;
echo "ro.hwui.path_cache_size=32" >> /system/build.prop;
echo "ro.hwui.gradient_cache_size=1" >> /system/build.prop;
echo "ro.hwui.drop_shadow_cache_size=6" >> /system/build.prop;
echo "ro.hwui.texture_cache_flushrate=0.4" >> /system/build.prop;
echo "ro.hwui.text_small_cache_width=1024" >> /system/build.prop;
echo "ro.hwui.text_small_cache_height=1024" >> /system/build.prop;
echo "ro.hwui.text_large_cache_width=2048" >> /system/build.prop;
echo "ro.hwui.text_large_cache_height=4096" >> /system/build.prop;
echo "" >> /system/build.prop;
echo "#flyme bootup properties" >> /system/build.prop;
echo "debug.gralloc.gfx_ubwc_disable=0" >> /system/build.prop;
echo "persist.radio.atfwd.start=true" >> /system/build.prop;
echo "ro.kernel.qemu.gles=0" >> /system/build.prop;
echo "sdm.debug.disable_scalar=0" >> /system/build.prop;
echo "sdm.debug.disable_inline_rotator=1" >> /system/build.prop;
echo "sdm.drop_skewed_vsync=1" >> /system/build.prop;
echo "ro.vendor.at_library=libqti-at.so" >> /system/build.prop;
echo "persist.vendor.qti.games.gt.prof=1" >> /system/build.prop;
echo "ro.vendor.qti.core_ctl_min_cpu=4" >> /system/build.prop;
echo "ro.vendor.qti.core_ctl_max_cpu=6" >> /system/build.prop;
echo "" >> /system/build.prop;
echo "#bootup properties for deflymized roms" >> /system/build.prop;
echo "ro.vendor.meizu_no_vts=1" >> /system/build.prop;
echo "persist.hvx.hwjpeg.enable=false" >> /system/build.prop;
echo "vendor.audio.adm.buffering.ms=3" >> /system/build.prop;
echo "vendor.audio.adm.buffering.ms=3" >> /system/build.prop;
echo "" >> /system/build.prop;
echo "#sdm brightness module" >> /system/build.prop;
echo "persist.sys.qcom-brightness=255" >> /system/build.prop;
echo "" >> /system/build.prop;
echo "#ui artefacts fix" >> /system/build.prop;
echo "debug.hwui.profile=true" >> /system/build.prop;
exit 0;